### ISSUE TITLE
Tracked achievements still marked as tracked after completion

### ISSUE THREAD

**Issue by Seriphe** [TheKrowi/Krowi_AchievementFilter#104]
Noticed today when trying to track new things and I got the error saying I could only track up to 10 (I can see 6 on the side). Checked my recent achevements, some are still showing as tracked despite being completed, with the oldest being marked 1/05/23. Can't find a way to untrack them.
![krowli](https://user-images.githubusercontent.com/122347917/214985068-479cb439-7c23-4c02-9c7c-19c4e4417d13.jpg)

**Comment by TheKrowi** [comment]
So the achievement was tracked, you earned it and they're still tracked? Does this resolve by reloading the game? Blizz made changes to their API when 10.0.0 launched and this might be an oversight on my end still.

**Comment by Seriphe** [comment]
Correct. They're tracked in the achievement window, but not the side list because they're completed. Relogging doesn't help, or that achievement I got on the 5th wouldn't still be checkmarked; and I have to reload every time I reach a new renown level because of another addon, so that doesn't help either. 

I tried to squeeze everything I could into the screenshot (error, side list, and the Jan 5 achievement).

(As a side note, thank you so much for this addon! I used to use Overachiever, and you have a lot more options than it did.)

**Comment by TheKrowi** [comment]
In the next release (coming soon) You'll be able to "track" those earned achievements and the tracking flag will be removed. I've also implemented a proper fix for the future when you earn an achievement, the tracking flag is also removed like Blizz does.
