### ISSUE TITLE
51.2+ doesn't play nice with the Wowhead Quick Link addon

### ISSUE THREAD

**Issue by Taizunz** [TheKrowi/Krowi_AchievementFilter#105]
Ever since 51.2 was released I've been unable to use the keybind associated with the Wowhead Quick Link addon when navigating achievements.
I'm aware that I can right-click an achievement and click the wowhead button to get a wowhead link as well using your addon, but having a keybind to instantly pop that same dialog up using the Wowhead Quick Link addon is just something I've been used to for years, so I've reverted to version 51.1 of your addon in order to make the two addons play nice again.

**Comment by TheKrowi** [comment]
I finally came around to check on this. I assume the problem will be that the achievement buttons in the new tabs are no "normal" achievements buttons so Wowhead Quick Link addon does not automatically recognize them. I'll add a plugin in KAF to support this addon.

**Comment by TheKrowi** [comment]
After further investigation, apparently I broke compatibility. I've opened a pull request with the other dev https://github.com/NielsHeltner/wowhead-quick-link/pull/24

**Comment by TheKrowi** [comment]
Since the author is not active right now, the new version of KAF will have a workaround.

![image](https://user-images.githubusercontent.com/22818581/227126212-12090517-7524-4974-b21f-1ff7cf18c1e2.png)

**Comment by vaindil** [comment]
Hey there, I'm so sorry for the delay in updating Wowhead Quick Link! I just merged your PR and pushed [version 2.15.3](https://www.curseforge.com/wow/addons/wowhead-quick-link/files/4453492). Thank you so much!

**Comment by TheKrowi** [comment]
Removing the workaround on my end again ;)
