### ISSUE TITLE
"Hidden" achievements don't show in watch list

### ISSUE THREAD

**Issue by Wevah** [TheKrowi/Krowi_AchievementFilter#113]
When I search for a hidden achievement (i.e., one that hasn't had the prior achievement unlocked, in this case "Thaldraszus Advanced: Gold"), and alt-click or choose "Add to Watch List" from the contextual menu, it appears to be added ("Add" changes to "Remove"), but it remains invisible in the watch list.

I couldn't find an issue for this yet, and I'm not sure how doable this is (or if it's even worth it), but I figured I should file an issue anyway.

**Comment by TheKrowi** [comment]
The reason why you don't see it is cause you have this filter checked.
![image](https://user-images.githubusercontent.com/22818581/222895401-1eb9376e-99a9-4554-bc5f-89b305ba0b60.png)

What this filter does is only show the next one in the chain which for me would've been Silver.
![image](https://user-images.githubusercontent.com/22818581/222895431-52c06e1c-1425-433e-9c3b-1428ed3cc5d3.png)

The way I'll fix this one is add a new setting to have "apply filters to watched achievements".
