### ISSUE TITLE
10.0.7 - Lua errors

### ISSUE THREAD

**Issue by Fargotroniac** [TheKrowi/Krowi_AchievementFilter#118]
Hello,

After update to new version of addon:

`Message: ...ce/AddOns/Krowi_AchievementFilter/Data/SavedData.lua:148: attempt to index global 'SavedData' (a nil value)
Time: Wed Mar 22 09:36:08 2023
Count: 1
Stack: ...ce/AddOns/Krowi_AchievementFilter/Data/SavedData.lua:148: attempt to index global 'SavedData' (a nil value)
[string "@Interface/AddOns/Krowi_AchievementFilter/Data/SavedData.lua"]:148: in function `solution'
[string "@Interface/AddOns/Krowi_AchievementFilter/Data/SavedData.lua"]:119: in function <...ce/AddOns/Krowi_AchievementFilter/Data/SavedData.lua:112>
[string "@Interface/AddOns/Krowi_AchievementFilter/Data/SavedData.lua"]:54: in function `Load'
[string "@Interface/AddOns/Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:49: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:34>
[string "@Interface/AddOns/Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:102: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:98>

Locals: prevBuild = "10.0.7"
currBuild = "10.0.7"
prevVersion = "53.1"
currVersion = "54.0"
firstTime = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'SavedData' (a nil value)"
diagnostics = <table> {
 TraceEnabled = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:36
 Debug = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:9
 DebugEnabled = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:33
 Print = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:41
 Trace = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:26
 Load = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:32
 DebugTable = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Diagnostics.lua:15
}
addon = <table> {
 ReplaceVarsWithReloadReq = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:545
 WorldMapButtons = <table> {
 }
 GUI = <table> {
 }
 SearchOptions = <table> {
 }
 Filters = <table> {
 }
 ExcludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:210
 Data = <table> {
 }
 GetAchievementNumCriteria = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:589
 ChangeAchievementMicroButtonOnClick = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:627
 Objects = <table> {
 }
 IsWrathClassic = false
 DelayObjects = <table> {
 }
 OnAchievementEarned = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:365
 DelayFunction = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:646
 Options = <table> {
 }
 Diagnostics = <table> {
 }
 IsCustomModifierKeyDown = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:673
 TooltipData = <table> {
 }
 EventData = <table> {
 }
 GlobalStrings = <table> {
 }
 MakeWindowMovable = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:525
 GetUsableSets = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:597
 Modifiers = <table> {
 }
 GetAchievementCriteriaInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:578
 GetNextAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:566
 ExtraWrathStrings = <table> {
 }
 Tabs = <table> {
 }
 GetInstanceInfoName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Localization/GlobalStrings.lua:10
 GetMapName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Localization/GlobalStrings.lua:38
 GetAchievementInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:554
 Util = <table> {
 }
 MetaData = <table> {
 }
 GetFirstAchievementId = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:3
 GetSecondsSince = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:535
 WatchAchievement = <function> defined @Interfac`
`Message: ...ace/AddOns/Krowi_AchievementFilter/Plugins/ElvUI.lua:670: hooksecurefunc(): setUpFunction is not a function
Time: Wed Mar 22 09:36:17 2023
Count: 1
Stack: ...ace/AddOns/Krowi_AchievementFilter/Plugins/ElvUI.lua:670: hooksecurefunc(): setUpFunction is not a function
[string "=[C]"]: ?
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/Krowi_AchievementFilter/Plugins/ElvUI.lua"]:670: in function <...ace/AddOns/Krowi_AchievementFilter/Plugins/ElvUI.lua:665>
[string "@Interface/AddOns/Krowi_AchievementFilter/Plugins/ElvUI.lua"]:679: in function `OnEvent'
[string "@Interface/AddOns/Krowi_AchievementFilter/Plugins/Plugins.lua"]:11: in function <...e/AddOns/Krowi_AchievementFilter/Plugins/Plugins.lua:8>

Locals: `
`Message: .../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:130: attempt to call field 'ShowActiveEventsOnPlayerEnteringWorld' (a nil value)
Time: Wed Mar 22 09:36:23 2023
Count: 1
Stack: .../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:130: attempt to call field 'ShowActiveEventsOnPlayerEnteringWorld' (a nil value)
[string "=[C]"]: in function `ShowActiveEventsOnPlayerEnteringWorld'
[string "@Interface/AddOns/Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:130: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:129>

Locals: `

**Comment by TheKrowi** [comment]
2nd error is probably caused by the first one. Please verify 54.1

**Comment by Fargotroniac** [comment]
Looks ok, thanks for fix.
