### ISSUE TITLE
Taint when setting Keybinds

### ISSUE THREAD

**Issue by Dreadful-Sanity** [TheKrowi/Krowi_AchievementFilter#121]
Recently (last update I think) Krowi produces very reliantly a taint-error when I'm changing keybinds and want to leave the window. From what I could find earlier during Dragonflight (different addon had the same issue) it had something to do with the custom keybind categories. Changed them back to addon and not getting taint.

Just a heads-up. It's nothing game-breaking. Just a tad annoying.

**Comment by TheKrowi** [comment]
Do you have a little more info for me about this cause it's pretty vague to me I'm afraid.

**Comment by Nils89** [comment]
Sounds like that one 
https://github.com/Stanzilla/WoWUIBugs/issues/371

But it will be fixed with 10.1.

**Comment by Dreadful-Sanity** [comment]
Ah, awesome. Thanks.

**Comment by TheKrowi** [comment]
Closing this for now asit looks like this one is fixed.
