### ISSUE TITLE
Cannot close tooltip using Esc key

### ISSUE THREAD

**Issue by Xadrakan** [TheKrowi/Krowi_AchievementFilter#129]
The tooltip opened by clicking an achievement link from chat cannot be closed using the Esc key, and can only be closed using the X button at the top-right corner of the tooltip. Using version 56.5 of the addon.

**Comment by TheKrowi** [comment]
Same behavior as the pet tooltip. Exc does not close it. Marking it as an improvement.

![image](https://github.com/TheKrowi/Krowi_AchievementFilter/assets/22818581/769c3e10-3e06-4680-9b25-2bdb21e8ae3a)

**Comment by TheKrowi** [comment]
Will be available in 10.1.5.
