### ISSUE TITLE
Lua error with 56.5 when logging in

### ISSUE THREAD

**Issue by b-morgan** [TheKrowi/Krowi_AchievementFilter#130]
22x Krowi_AchievementFilter/Data/TooltipData.lua:105: attempt to index field 'Tooltip' (a nil value)
[string "@Krowi_AchievementFilter/Data/TooltipData.lua"]:105: in function <Krowi_AchievementFilter/Data/TooltipData.lua:104>
[string "@Krowi_AchievementFilter/Data/TooltipData.lua"]:175: in function <Krowi_AchievementFilter/Data/TooltipData.lua:174>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
...
[string "@FishingBuddy/Libs/LibFishing-1.0-101108/LibFishing-1.0.lua"]:2365: in function `FishingBonusPoints'
[string "@FishingBuddy/Libs/LibFishing-1.0-101108/LibFishing-1.0.lua"]:1503: in function `IsFishingGear'
[string "@FishingBuddy/Libs/LibFishing-1.0-101108/LibFishing-1.0.lua"]:1895: in function `GetFishingSkillLine'
[string "@FB_Broker/FB_Broker.lua"]:69: in function `UpdateSkill'
[string "@FB_Broker/FB_Broker.lua"]:85: in function <FB_Broker/FB_Broker.lua:84>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@FishingBuddy/FishingBuddy.lua"]:448: in function <FishingBuddy/FishingBuddy.lua:435>

Locals:
tooltip = FishLibTooltip {
 0 = <userdata>
 shownMoneyFrames = 1
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetPrimaryTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:499
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:410
 shouldRefreshData = true
 RefreshData = <function> defined @FrameXML/GameTooltip.lua:1055
 SetItemKey = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 HasDataInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:514
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 CIMI_tooltipWritten = true
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 hasMoney = 1
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:492
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 numMoneyFrames = 1
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 infoList = <table> {
 }
 SetAzeriteEssenceSlot = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 processingInfo = <table> {
 }
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:1112
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetLFGDungeonReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 updateTooltipTimer = 0
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:1116
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 supportsDataRefresh = true
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:400
 NineSlice = Frame {
 }
 SetCompanionPet = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 StatusBar = FishLibTooltipStatusBar {
 }
 SetAchievementByID = <functio

**Comment by TheKrowi** [comment]
It looks like another addon is trying to show a tooltip while KAF is not yet loaded. This is causing an error in KAF. Any idea which addon it might be? `FB_Broker/FB_Broker.lua` `LibFishing-1.0.lua` some fishing addon?

**Comment by b-morgan** [comment]
This error happens most often when I "/reload". I am the author of Skillet-Classic and when debugging it, I will make changes to the .lua files and "/reload" to make them take effect.

Since this error happens before the UI is active, I don't know which, if any, addon is triggering it.

The addon Fishing Buddy appears in the traceback but I'm not actively fishing when the "/reload" happens. I can try disabling it to see what other addon might appear in the traceback if you think that will help.

**Comment by TheKrowi** [comment]
What I think is happening is, is that something is trying to show a tooltip somewhere. KAF hooks into it to show additional stuff for achievements but fires on any tooltip show (unfortunately). When showing a tooltip and it's achievement related, I do some checks to see if it should show that additional content or not (user options). The thing causing this error is that the user options aren't loaded yet but the code apparently already is hooked.

**Comment by b-morgan** [comment]
Seems like you need to add another check in the hooked code. I have noticed that while "/reload" does execute code that runs when you "logoff" (i.e. saved variables) and "logon" (i.e. reload .lua and .xml files), it doesn't completely reset all the variables associated with an addon.

I just checked and the PLAYER_LOGOUT event is fired when a "/reload" is entered.

**Comment by TheKrowi** [comment]
If the issue still remains with the current version of KAF, please let me know.
