### ISSUE TITLE
API.lua:79: attempt to index local 'category' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [TheKrowi/Krowi_AchievementFilter#132]
I was clicking on the event toasts as they were popping up after logging in and received an error for one of them, ( I think it's for the Elemental Storms). Clicking on the toast for "Slagmire" and also the tab from the achievement UI caused the following error. The other tabs cause no issue and opened their respective achievement. Thanks.

Edit: It's for the Elemental Storms, not Primalist Invasions.

![Screenshot 2023-06-21 181358_2](https://github.com/TheKrowi/Krowi_AchievementFilter/assets/26803942/f45188de-72ee-4cf4-94df-7e37bd3d2802)

16x Krowi_AchievementFilter/API.lua:79: attempt to index local 'category' (a nil value)
[string "@Krowi_AchievementFilter/API.lua"]:79: in function `KrowiAF_SelectCategory'
[string "@Krowi_AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua"]:18: in function <...AchievementFilter/GUI/Misc/AlertFrame/AlertFrame.lua:4>

Locals:
category = nil
collapsed = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'category' (a nil value)"
addon = <table> {
 ReplaceVarsWithReloadReq = <function> defined @Krowi_AchievementFilter/Globals.lua:543
 WorldMapButtons = <table> {
 }
 GUI = <table> {
 }
 SearchOptions = <table> {
 }
 Filters = <table> {
 }
 ExcludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:210
 Data = <table> {
 }
 BuildCache = <function> defined @Krowi_AchievementFilter/Globals.lua:323
 ChangeAchievementMicroButtonOnClick = <function> defined @Krowi_AchievementFilter/Globals.lua:625
 Objects = <table> {
 }
 IsWrathClassic = false
 DelayObjects = <table> {
 }
 OnAchievementEarned = <function> defined @Krowi_AchievementFilter/Globals.lua:365
 DelayFunction = <function> defined @Krowi_AchievementFilter/Globals.lua:644
 Options = <table> {
 }
 Diagnostics = <table> {
 }
 IsCustomModifierKeyDown = <function> defined @Krowi_AchievementFilter/Globals.lua:671
 TooltipData = <table> {
 }
 EventData = <table> {
 }
 GlobalStrings = <table> {
 }
 MakeWindowMovable = <function> defined @Krowi_AchievementFilter/Globals.lua:523
 GetUsableSets = <function> defined @Krowi_AchievementFilter/Globals.lua:595
 Modifiers = <table> {
 }
 GetAchievementCriteriaInfo = <function> defined @Krowi_AchievementFilter/Globals.lua:576
 GetNextAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:564
 ExtraWrathStrings = <table> {
 }
 Tabs = <table> {
 }
 GetInstanceInfoName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:10
 GetMapName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:38
 GetAchievementInfo = <function> defined @Krowi_AchievementFilter/Globals.lua:552
 Util = <table> {
 }
 MetaData = <table> {
 }
 GetFirstAchievementId = <function> defined @Krowi_AchievementFilter/Globals.lua:3
 GetSecondsSince = <function> defined @Krowi_AchievementFilter/Globals.lua:533
 WatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:160
 InGuildView = <function> defined @Krowi_AchievementFilter/Globals.lua:12
 TrackingAchievements = <table> {
 }
 GetAchievementsInZone = <function> defined @Krowi_AchievementFilter/Globals.lua:20
 MakeWindowStatic = <function> defined @Krowi_AchievementFilter/Globals.lua:483
 GetVariantSetIDs = <function> defined @Krowi_AchievementFilter/Globals.lua:607
 TabsOrder = <table> {
 }
 ResetCache = <function> defined @Krowi_AchievementFilter/Globals.lua:353
 HookFunctions = <function> defined @Krowi_AchievementFilter/Globals.lua:452
 OverwriteFunctions = <function> defined @Krowi_AchievementFilter/Globals.lua:387
 Plugins = <table> {
 }
 L = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Krowi_AchievementFilter/Globals.lua:16
 GetAchievementNumCriteria = <function> defined @Krowi_AchievementFilter/Globals.lua:587
 GetAchievementNumbers = <function> defined @Krowi_AchievementFilter/Globals.lua:51
 GetCategoryInfoTitle = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:22
 PluginStrings = <table> {
 }
 AddToTrackingAchievementsCategories = <function> defined @Krowi_AchievementFilter/Globals.lua:174
 Event = <table> {
 }
 IncludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:187
 IsDragonflightRetail = true
 Tutorials = <table> {
 }
 GetLFGDungeonInfo = <function> defined @Krowi_Achieve

**Comment by TheKrowi** [comment]
I hope to have this fixed in 10.1.5. Hard to test though as these events are not always up.
