### ISSUE TITLE
Unable to track incomplete achievements that are completed on another toon

### ISSUE THREAD

**Issue by tflo** [TheKrowi/Krowi_AchievementFilter#161]
In Krowi, somehow I'm unable to track achievements that have been completed on another char (but not on the current one).

As an example, the current Brewfest achieve "A Round on the House":

<img width="624" alt="WoWScrnShot_092123_155554" src="https://github.com/TheKrowi/Krowi_AchievementFilter/assets/1410282/a1097b46-8763-4b29-88bd-5102425182c0">

I would like to track this because it's still uncompleted on this toon, and each criterion rewards Brewfest tokens. And in order to do that comfortably, I need to be able to see quickly which taverns are missing on the current toon. (Since I have 17 toons in DF, memory is failing me here ;)

Probably I'm just missing a setting to disable that behavior(?) But the only workaround I've found so far is to activate the Blizz standard achievements tab and click the checkbox there.

**Comment by TheKrowi** [comment]
In the Filters you need to set the `Earned By` to `Character / Account` in order to track on alts that did not earn the achievement yet but another one does.

![image](https://github.com/TheKrowi/Krowi_AchievementFilter/assets/22818581/c73407eb-474f-4189-907b-18cb13e33836)

**Comment by TheKrowi** [comment]
`Account` is really meant for people who don't care about alts and only want to earn the achievement once.

**Comment by tflo** [comment]
Ahhhh…, thank you very much! I never would have looked there (I assumed this menu was just about filtering which achievements to _show_, and since it _is_ being shown...)

**Comment by tflo** [comment]
PS:

> `Account` is really meant for people who don't care about alts and only want to earn the achievement once.

Actually this is true for me (only doing achieves once), but this achievement is an exception, as it rewards stuff per criterion and on each toon.
