### ISSUE TITLE
WotLK 3.4.2 - Opening the achievement frame results in an error.

### ISSUE THREAD

**Issue by godsyn** [TheKrowi/Krowi_AchievementFilter#162]
Version info:

- Wow: WotLK 3.4.2 
- Addon: 10.1.7 (63.2?)

Opening the frame results in:
```
4x ...ns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua:346: attempt to get length of local 'buttons' (a nil value)
[string "@Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:346: in function `AchievementFrameCategories_Update'
[string "@Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:273: in function <...ns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua:272>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Krowi_AchievementFilter/Globals.lua"]:420: in function `AchievementFrame_ToggleAchievementFrame'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:573: in function `ToggleAchievementFrame'
[string "TOGGLEACHIEVEMENT"]:1: in function <[string "TOGGLEACHIEVEMENT"]:1>

Locals:
scrollFrame = AchievementFrameCategoriesContainer {
 0 = <userdata>
 scrollDown = AchievementFrameCategoriesContainerScrollBarScrollDownButton {
 }
 scrollChild = AchievementFrameCategoriesContainerScrollChild {
 }
 ScrollChild = AchievementFrameCategoriesContainerScrollChild {
 }
 scrollUp = AchievementFrameCategoriesContainerScrollBarScrollUpButton {
 }
 scrollBar = AchievementFrameCategoriesContainerScrollBar {
 }
}
categories = <table> {
}
offset = 0
buttons = nil
displayCategories = <table> {
}
selection = "summary"
parent = nil
numCategories = 0
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'buttons' (a nil value)"
displayCategories = <table> {
}
```
Note : this only occurs on my main. On alts it doesn't happen. Deleting `SavedVariables\Krowi_AchievementFilter.lua` doesn't resolve the issue

**Comment by TheKrowi** [comment]
I'm not able to reproduce it. Do you have certain addons enabled on your main and not on alts?
Reason for asking is cause it looks like the default blizz ui is bugging out and not KAF.

**Comment by godsyn** [comment]
I have billions (hyperbole) of add-ons. I'll further troubleshoot and see
if it is related to any other specific addon.

I apologize for the delay, but this may take a couple of days.

**Comment by godsyn** [comment]
Incompatible addon found. 
`Talented_SpecTabs`
Part of the talented package: https://www.curseforge.com/wow/addons/talented

**Comment by TheKrowi** [comment]
Are you a 100% sure? If so I'll have a look into it but don't expect anything soon unfortunately as I'm very busy irl the coming days/weeks.

**Comment by TheKrowi** [comment]
Could you maybe also provide me with a minimal addon set I have to install to reproduce it? This would save me some time :)

**Comment by godsyn** [comment]
Big ole' case of "It's not you, its me." Custom addon was causing it. My apologies.
