### ISSUE TITLE
ADDON_ACTION_FORBIDDEN: Tried to call the protected function 'resume()'.

### ISSUE THREAD

**Issue by hayatofujii** [TheKrowi/Krowi_AchievementFilter#163]
This happens on login and reloads, albeit not reliably. Rolling back to the 62.x series doesn't trigger this.

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Krowi_AchievementFilter' tried to call the protected function 'resume()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@Krowi_AchievementFilter/Globals.lua"]:379: in function <Krowi_AchievementFilter/Globals.lua:376>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

**Comment by TheKrowi** [comment]
Do you happen to be in combat?

**Comment by hayatofujii** [comment]
> Do you happen to be in combat?

Nope!

**Comment by TheKrowi** [comment]
Apparently a known issue atm plaguing multiple addons: https://github.com/Stanzilla/WoWUIBugs/issues/483. Nothing we can do about it atm.

**Comment by hayatofujii** [comment]
Intesting. (https://github.com/Stanzilla/WoWUIBugs/issues/483)'s description matches the situation I'm seeing - the most annoying, not reliably reproducing after a few reloads and requiring a full login/logout sequence to trigger it.

Probably NOT related, but the after the taint happens, the cache coroutine dies. Not being fluent in lua, I thought that the OnUpdate hook was trying to resume it. Not sure about the correct sequence tho.
