### ISSUE TITLE
Addon directlyx after Logon

### ISSUE THREAD

**Issue by Pantasaron** [TheKrowi/Krowi_AchievementFilter#165]
Getting following error directly after logon after installing version 64.0

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Krowi_AchievementFilter' hat versucht die geschützte Funktion 'resume()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@Krowi_AchievementFilter/Globals.lua"]:379: in function <Krowi_AchievementFilter/Globals.lua:376>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by TheKrowi** [comment]
See #163
