### ISSUE TITLE
AceLocal-3.0-6: Krowi_AchievementFilter: Missing entry for ...

### ISSUE THREAD

**Issue by Xyrgia** [TheKrowi/Krowi_AchievementFilter#166]
AceLocale-3.0-6: Krowi_AchievementFilter: Missing entry for 'Not Completed'
[string "@Krowi_AchievementFilter/Tutorials.lua"]:100: in function `Load'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:54: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:34>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:101: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:98>

and

AceLocale-3.0-6: Krowi_AchievementFilter: Missing entry for 'Completed'
[string "@Krowi_AchievementFilter/Tutorials.lua"]:99: in function `Load'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:54: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:34>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:101: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:98>

WotLK, german game version, KAF version 64.0

**Comment by TheKrowi** [comment]
It looks like your data is corrupt as the error message does not match any lines in version 64.0. `Tutorials.lua` lines are off by 1 and for `Krowi_AchievementFilter.lua` I can;t match them to anything.

**Comment by Xyrgia** [comment]
have now used the release from github, some behavior

How can I give you more information?

**Comment by Xyrgia** [comment]
only KAF and bugsack activated with new character:

1x AceLocale-3.0-6: Krowi_AchievementFilter: Missing entry for 'Completed'
[string "@Krowi_AchievementFilter/Tutorials.lua"]:98: in function `Load'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:64: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:37>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:109: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:105>

1x AceLocale-3.0-6: Krowi_AchievementFilter: Missing entry for 'Not Completed'
[string "@Krowi_AchievementFilter/Tutorials.lua"]:99: in function `Load'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:64: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:37>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:109: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:105>

**Comment by Xyrgia** [comment]
fixed with KAF 64.1
