### ISSUE TITLE
Lua error with 66.0 - does not occur when using 65.0

### ISSUE THREAD

**Issue by Mike160770** [TheKrowi/Krowi_AchievementFilter#181]
1x Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:132: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua"]:132: in function `SetAchievementFrameHeight'
[string "@Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua"]:82: in function `LoadWithBlizzard_AchievementUI'
[string "@Interface/AddOns/Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:70: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:69>
[string "@Interface/AddOns/Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:112: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:106>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:677: in function `AchievementFrame_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:923: in function `ToggleAchievementFrame'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:728: in function <Interface/FrameXML/MainMenuBarMicroButtons.lua:726>
[string "=[C]"]: ?

Locals:
self = <table> {
 Calendar = <table> {
 }
 OverwriteAdjustAnchors = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:453
 WorldMapButton = <table> {
 }
 PrepareTabsOrder = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:144
 RefreshView = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:386
 SummaryFrame = <table> {
 }
 ShowStatusBarTooltip = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:268
 EventReminderAlertSystem = <table> {
 }
 RefreshViewAfterPlayerLogin = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:395
 LoadWithAddon = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:9
 Tabs = <table> {
 }
 AchievementsObjectives = <table> {
 }
 LoadWithBlizzard_AchievementUI = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:78
 EventReminderSideButtonSystem = <table> {
 }
 SetFrameToLastPosition = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:370
 AchievementTooltip = <table> {
 }
 FloatingAchievementTooltip = <table> {
 }
 FilterButton = <table> {
 }
 TabsOrderGetActiveKeys = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:352
 DataManager = <table> {
 }
 UpdateTabsLayout = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:219
 ResetAchievementFrameWidth = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:127
 RightClickMenu = <table> {
 }
 HandleCloseButtonOnKeyDown = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:421
 CategoriesFrame = <table> {
 }
 AchievementsFrame = <table> {
 }
 AchievementFrameTabButtonFactory = <table> {
 }
 SetAchievementFrameHeight = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:131
 AchievementFrameHeader = <table> {
 }
 SubFrames = <table> {
 }
 ResetAchievementFrameHeight = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:138
 ShowHideTabs = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:234
 ToggleAchievementFrame = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:185
 SetAchievementFrameWidth = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:122
 Search = <table> {
 }
 RegisterSafeCloseButtonDuringCombat = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:406
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
addon = <table> {
 WorldMapButtons = <table> {
 }
 ExcludeAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:210
 Diagnostics = <table> {
 }
 BuildCacheAsync = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:362
 GetAchievementInfoTable = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:644
 GetUsableSets = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:708
 Modifiers = <table> {
 }
 Metadata = <table> {
 }
 IsCustomModifierKeyDown = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:766
 GetInstanceInfoName = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Localization/GlobalStrings.lua:8
 ChangeAchievementMicroButtonOnClick = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:738
 Util = <table> {
 }
 IsWrathClassic = false
 WatchAchievement = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:159
 SearchOptions = <table> {
 }
 GetAchievementsInZone = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:20
 GetVariantSetIDs = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Globals.lua:720
 GetLFGDungeonInfo = <function> defined @Interface/AddOns/Krowi_AchievementFilter/Localization/GlobalStrings.lua:32
 Plugins = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Interface/AddOns/Krowi_Achievement

**Comment by Pantasaron** [comment]
Getting following error after logon, after updating to 66

1x ...mentFilter/Libs/Krowi_Util/Options/InjectOptions.lua:63: attempt to index local 'destTable' (a nil value)
[string "@Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua"]:63: in function `TableExists'
[string "@Krowi_AchievementFilter/API.lua"]:392: in function `KrowiAF_RegisterDeSelectAllEventOptions'
[string "@Krowi_AchievementFilter/Data/Retail/ExportedWidgetEvents.lua"]:40: in function `InjectDynamicOptions'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:43: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:37>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:110: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:106>

Locals:
self = <table> {
 TableExists = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:59
 PlusPlusAutoOrder = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:30
 GetTable = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:50
 AutoOrderPlusPlus = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:24
 AddPluginTable = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:86
 AdjustedWidth = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:19
 AddTable = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:35
 DefaultsExists = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:77
 AddDefaults = <function> defined @Krowi_AchievementFilter/Libs/Krowi_Util/Options/InjectOptions.lua:68
}
destTablePath = "EventReminders.args.WorldEvents.args.Dragonflight.args.Gemeinschaftliches_Festmahl_.args.SelectAll"
destTable = nil
pathParts = <table> {
 1 = "EventReminders"
 2 = "args"
 3 = "WorldEvents"
 4 = "args"
 5 = "Dragonflight"
 6 = "args"
 7 = "Gemeinschaftliches_Festmahl_"
 8 = "args"
 9 = "SelectAll"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "EventReminders"
 2 = "args"
 3 = "WorldEvents"
 4 = "args"
 5 = "Dragonflight"
 6 = "args"
 7 = "Gemeinschaftliches_Festmahl_"
 8 = "args"
 9 = "SelectAll"
}
(for control) = 6
_ = 6
part = "args"
(*temporary) = 6
(*temporary) = "attempt to index local 'destTable' (a nil value)"
addon = <table> {
 WorldMapButtons = <table> {
 }
 ExcludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:210
 Diagnostics = <table> {
 }
 BuildCacheAsync = <function> defined @Krowi_AchievementFilter/Globals.lua:362
 GetAchievementInfoTable = <function> defined @Krowi_AchievementFilter/Globals.lua:644
 GetUsableSets = <function> defined @Krowi_AchievementFilter/Globals.lua:708
 Modifiers = <table> {
 }
 Metadata = <table> {
 }
 IsCustomModifierKeyDown = <function> defined @Krowi_AchievementFilter/Globals.lua:766
 GetInstanceInfoName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:8
 ChangeAchievementMicroButtonOnClick = <function> defined @Krowi_AchievementFilter/Globals.lua:738
 Util = <table> {
 }
 IsWrathClassic = false
 WatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:159
 SearchOptions = <table> {
 }
 GetAchievementsInZone = <function> defined @Krowi_AchievementFilter/Globals.lua:20
 GetVariantSetIDs = <function> defined @Krowi_AchievementFilter/Globals.lua:720
 GetLFGDungeonInfo = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:32
 Plugins = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Krowi_AchievementFilter/Globals.lua:16
 GetAchievementNumCriteria = <function> defined @Krowi_AchievementFilter/Globals.lua:691
 Options = <table> {
 }
 AddToTrackingAchievementsCategories = <function> defined @Krowi_AchievementFilter/Globals.lua:172
 Event = <table> {
 }
 IsDragonflightRetail = true
 Data = <table> {
 }
 TooltipData = <table> {
 }
 EventData = <table> {
 }
 OnAchievementEarned = <function> defined @Krowi_AchievementFilter/Globals.lua:403
 GetNextAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:668
 Tabs = <table> {
 }
 Faction = <table> {
 }
 Libs = <table> {
 }
 LoadBlizzardApiChanges = <function> defined @Krowi_AchievementFilter/Globals.lua:481
 GetCategoryInfoTitle = <function> defined @Inter

**Comment by TheKrowi** [comment]
@Pantasaron that one should be fixed in 66.1, just pushed it.
@Mike160770 can you please let me know if yours is too?

The problem was non English clients.

**Comment by Kammihou** [comment]
Unfortunately 66.1 does not Fix it on German Client

**Comment by TheKrowi** [comment]
So the `1x Interface/AddOns/Krowi_AchievementFilter/Gui/Gui.lua:132: attempt to index field 'db' (a nil value)` is still a problem?

**Comment by Kammihou** [comment]
Sorry, my bad. It Works now ...

**Comment by Pantasaron** [comment]
Works like a charm .. thanks
