### ISSUE TITLE
undo stop tracking

### ISSUE THREAD

**Issue by Fokusrite** [TheKrowi/Krowi_AchievementFilter#189]
Hi. Sorry to bother you but is there a way to undo a timer on the right side of the achievements window if I click on "stop tracking" by mistake? I clicked like this on two or so timers like superbloom and some more but I want that back if possible without resetting whole addon. Thank You!

**Comment by Malivil** [comment]
You can re-enable them in the addon options under Event Reminders

**Comment by Fokusrite** [comment]
Thank You so much!
