### ISSUE TITLE
while the addon is active the achievment search doesn't work

### ISSUE THREAD

**Issue by Leosh11** [TheKrowi/Krowi_AchievementFilter#194]
while i got the addon active the achievment search aiN't functioning and the very supportive event thing on the right doesn't send me to the achievment list when i click on it... is there like a log i can send you to help?

**Comment by TheKrowi** [comment]
There is not a log no. Have you tried it without any other addons enabled?

**Comment by Leosh11** [comment]
thanks buddy, for some reason i had overarchiver was still installed and became out of date with the latest patch... that caused problems! love the addon btw great job
