### ISSUE TITLE
Move the calendar icon

### ISSUE THREAD

**Issue by zivilyyyn** [TheKrowi/Krowi_AchievementFilter#200]
Is it possible to move the calendar icon on the achievement window? It overlaps with elements from other addons.

**Comment by zivilyyyn** [comment]
> What other addons? Do you have pictures?

Achievement back button

https://www.curseforge.com/wow/addons/achievements-back-button

I know I can move the back button to other positions. But for me the back button fits better in this position. So I want to move the calendar button to the other side of the title of the achievement window. 😁

**Comment by TheKrowi** [comment]
I was actually working on a fewture like that 😅. I see what I can do :)

**Comment by TheKrowi** [comment]
Potential fix and integration of the feature in KAF: https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/71.0-beta1

**Comment by TheKrowi** [comment]
Implemented in 71.0
