### ISSUE TITLE
Categories in Watch List are all "Unknown"

### ISSUE THREAD

**Issue by tflo** [TheKrowi/Krowi_AchievementFilter#210]
When I activate the categories for my Watch List…

<img width="606" alt="image" src="https://github.com/TheKrowi/Krowi_AchievementFilter/assets/1410282/ec23d52d-c7cb-48f4-8d16-e06a7202bb98">

…then it looks like this:

<img width="996" alt="image" src="https://github.com/TheKrowi/Krowi_AchievementFilter/assets/1410282/3b8b9d0f-25b1-4743-be79-66dfc5ae3ad9">

This is only in the Watch List, otherwhere the categories are displayed correctly (AFAICT).

---

Krowi 72.2 with WoW Retail en-US

**Comment by TheKrowi** [comment]
Same issue with Excluded

**Comment by tflo** [comment]
Thanks for the super fast fix 🥰
