### ISSUE TITLE
Lua error when hovering over next/previous buttons

### ISSUE THREAD

**Issue by Sluimerstand** [TheKrowi/Krowi_AchievementFilter#212]
![image](https://github.com/TheKrowi/Krowi_AchievementFilter/assets/29845810/36e18082-08f3-46a5-8565-ce33e30bbc5a)
These buttons. When the buttons are both disabled and there is no next/previous achievement to go to, this error pops up:

```
26x ...vementFilter/Gui/BrowsingHistory/BrowsingHistory.lua:38: attempt to index local 'category' (a nil value)
[string "@Krowi_AchievementFilter/Gui/BrowsingHistory/BrowsingHistory.lua"]:38: in function <...vementFilter/Gui/BrowsingHistory/BrowsingHistory.lua:36>
[string "@Krowi_AchievementFilter/Gui/BrowsingHistory/BrowsingHistory.lua"]:61: in function <...vementFilter/Gui/BrowsingHistory/BrowsingHistory.lua:46>
[string "@Krowi_AchievementFilter/Gui/BrowsingHistory/BrowsingHistory.lua"]:89: in function <...vementFilter/Gui/BrowsingHistory/BrowsingHistory.lua:85>```

**Comment by TheKrowi** [comment]
Should be fixed with last release. What version are you currently on and can you still reproduce it?

**Comment by Sluimerstand** [comment]
I can currently not reproduce it on either 72.2 nor 72.3, so it seems fine currently. Might have been because I'd just adjusted some settings, also. Thanks for the quick response. :)

**Comment by TheKrowi** [comment]
It was caused when you browsed the `Watch List` or `Excluded` achievements.
