### ISSUE TITLE
GitHub Donation Button not working

### ISSUE THREAD

**Issue by StanoRiga** [TheKrowi/Krowi_AchievementFilter#227]
Hi. I wanted to donate via Paypal and avoid using the curseforge, etc option, because I am not sure if donation via these Plattform are going completely to the author. So I wanted to use the Paypal donation button shown on this Github repository under "support me". Unfortunately the button does not work. It shows the message: "The page of this organisation does not work".

**Comment by TheKrowi** [comment]
I had a look, github indeed wasn't working, curseforge was though for me. Just fyi, curseforge does not keep anything as they live from adds. Everything goes to the creator except for transaction costs paypal takes.
