### ISSUE TITLE
Achievements window opens off-screen

### ISSUE THREAD

**Issue by InvisiBilldotnet** [TheKrowi/Krowi_AchievementFilter#32]
Whenever I first open the Achievements window, the top half is off the top of my screen (2560x1440).  I can switch to the Guild tab, which makes a shorter window, and drag the window lower by the now-visible title bar.  Once the window has been moved lower, I can switch back to the personal Achievements tab and see the whole window.

**Comment by TheKrowi** [comment]
Do you have a screenshot of what you mean?

**Comment by InvisiBilldotnet** [comment]
When initially opened, the Achievements window is partially off the top of the screen.
![image](https://user-images.githubusercontent.com/21955683/196262582-0121bdbf-a569-47ad-8e14-623196c22059.png)

Switching to the smaller Guild tab brings it fully on screen.  The bottom of the window seems to be the anchor point.
![image](https://user-images.githubusercontent.com/21955683/196262621-24601a94-093a-4155-acda-5e0ac832ac49.png)

If the window is dragged a tiny bit while on the Guild tab, the top of the window seems to become the anchor point, and the window will be fully on screen when I switch back to the Achievements tab.
![image](https://user-images.githubusercontent.com/21955683/196262656-776acee9-5b5f-43dc-a13a-cbf61a8cd35c.png)

The position will occasionally reset to the initial off-screen location while I'm playing.  One example is when I port to a new zone (took the portal from Sinfall to Oribos after taking these screenshots).

**Comment by TheKrowi** [comment]
As far as I know you're the only one that has this problem at this moment. Any chance there is an addon that might cause this you can think of?

**Comment by TheKrowi** [comment]
@InvisiBilldotnet, any update? Have you tried KAF without any other addons enabled?

**Comment by InvisiBilldotnet** [comment]
I didn't get a chance to try it without other addons.  However, I started 10.0 by purging most of my addons due to not being updated, and KAF's window now behaves as expected.  If the issue returns when I re-add other addons as they get updated, it should be a lot easier to narrow down the source of the problem.  For now, I'd say KAF is in the clear.

**Comment by TheKrowi** [comment]
K cool, happy it is resolved for now. :)
