### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by whichwit** [TheKrowi/Krowi_AchievementFilter#37]
Not sure where the addon gets its data, some are not accurate. For instance, [Ultimate Triage](https://www.wowhead.com/wotlk/achievement=141/ultimate-triage) is filtered as _No Longer Available_, however it can be completed in game.

**Comment by TheKrowi** [comment]
Hey, I'm aware wrath classic has some inconsistencies still. I hope to resolve these soon. I did not expect blizzard to start on version 3.4.0 so all data was added expecting 3.0.1 to be the release...

**Comment by TheKrowi** [comment]
Having a closer look now, not all  achievements are ported from the legacy system to the new system, Ultimate Triage being one of them. I'll go over these missing ones too before the next version.

**Comment by TheKrowi** [comment]
Most should be fixed by now for Wrath Classic. I'm closing this issue, if you got something more, please let me know.
