### ISSUE TITLE
Compatability issue with ElvUI

### ISSUE THREAD

**Issue by Beet4** [TheKrowi/Krowi_AchievementFilter#40]
Some elements on the top of the Achievement window looks a bit weird with this addon together with ElvUI:
![image](https://user-images.githubusercontent.com/38279393/198255147-1cdffa24-e649-483e-87bf-a012be52f76d.png)

**Comment by TheKrowi** [comment]
I'm aware of this but forgot about it, oops. I was waiting for ElvUI to fix things before fiddling around with it. Something that will be included in the next version. Thank you for reminding me ;)

**Comment by Beet4** [comment]
Awesome, thanks! :)

Just found your addon as Overachiever seems abandoned. Hope this can be a good substitute

**Comment by TheKrowi** [comment]
This is how Wrath Classic looks and Shadowlands used to look like. Restore this in Dragonflight.
![image](https://user-images.githubusercontent.com/22818581/198523199-c46c7807-43a8-4ed5-b324-02ccaaa807b9.png)

**Comment by TheKrowi** [comment]
This is without KAF.
![image](https://user-images.githubusercontent.com/22818581/198523665-37f5ea55-5b1f-43de-8ef4-9a2ac4777e07.png)
