### ISSUE TITLE
Feature Request: Achievement reminder info in object/NPC tooltip

### ISSUE THREAD

**Issue by filliph** [TheKrowi/Krowi_AchievementFilter#53]
The only feature I'm currently missing from Overachiever is the reminder info in tooltips:

![image](https://user-images.githubusercontent.com/9424286/199211886-af217072-637d-4548-a162-39203881cb92.png)

This is invaluable when going through areas for Loremaster or some such. I do realise that it would be a lot of work, so if you were to build the framework for this feature, I would be more than happy to help with converting the Overachiever data to your preferred format so we could get this feature implemented 🙂 

Thank you for considering!

**Comment by Malivil** [comment]
They are already working on it =)
They have a little preview thread of their discord to show the progress.

**Comment by filliph** [comment]
Gotcha, I'll follow on Discord, thank you 😄
