### ISSUE TITLE
Bug During Edit Mode

### ISSUE THREAD

**Issue by vandiel01** [TheKrowi/Krowi_AchievementFilter#54]
This pops up when/while in Edit Mode

> 2x [ADDON_ACTION_FORBIDDEN] AddOn 'Krowi_AchievementFilter' tried to call the protected function 'ClearTarget()'.
> [string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:519: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:519>
> [string "=[C]"]: in function `ClearTarget'
> [string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
> [string "@Interface/FrameXML/EditModeManager.lua"]:1479: in function `OnEditModeExit'
> [string "@Interface/FrameXML/EditModeManager.lua"]:185: in function `ExitEditMode'
> [string "@Interface/FrameXML/EditModeManager.lua"]:205: in function <Interface/FrameXML/EditModeManager.lua:203>
> [string "=[C]"]: in function `Hide'
> [string "@Interface/FrameXML/UIParent.lua"]:2828: in function `SetUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2859: in function `MoveUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2890: in function `HideUIPanel'
> [string "@Interface/FrameXML/UIParent.lua"]:2556: in function <Interface/FrameXML/UIParent.lua:2548>
> [string "=[C]"]: in function `SetAttribute'
> [string "@Interface/FrameXML/UIParent.lua"]:3170: in function `HideUIPanel'
> [string "@Interface/FrameXML/EditModeManager.lua"]:122: in function `onCloseCallback'
> [string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:127: in function <Interface/SharedXML/SharedUIPanelTemplates.lua:122>

**Comment by TheKrowi** [comment]
Are there some steps I can do to reproduce this? Would make it easier for me to check what might be wrong :)

**Comment by Hyphie24** [comment]
It happens with all addons, it's an issue with the edit mode

**Comment by TheKrowi** [comment]
This is a Blizzard issue addon devs can't do anything about it. Will be fixed with DF release. See https://github.com/Stanzilla/WoWUIBugs/issues/256 for more information.
