### ISSUE TITLE
Locale is not taken into account by LUA standard functions

### ISSUE THREAD

**Issue by Gerokusu** [TheKrowi/Krowi_AchievementFilter#63]
**Problem**

When using EventReminders, the formatted date are printed in english no matter what locale you are using.

![image](https://user-images.githubusercontent.com/5943570/200174910-ddc81b9d-c2dd-42ba-b35b-4a5aa3a97207.png)

I am using French, on the screenshot above it should be set as "Novembre" (reversed E / R). After investigating the code, it looks like the standard LUA functions do not understand the current locale, as according to the [standard documentation](https://www.lua.org/pil/22.1.html) they should have this responsibility.

I checked with `print(GetLocale())` just before `AlertFrameMixin.lua:26`, the result is frFR for me, which is correct.

**Proposition**

A quick win would be to get the date month index, use an array of months in the translation files, and hard print this value directly into the string, ignoring the %B format. It is quite dirty though and ignores a normally standard way of operating.

**Comment by TheKrowi** [comment]
I assume this is the same for both Wrath Classic and Dragonflight?

**Comment by Gerokusu** [comment]
I did not test it on Classic, only on Dragonflight, but I assume it should have the same behaviour.

**Comment by TheKrowi** [comment]
@Gerokusu just wondering, is your pc in French or English?

**Comment by Gerokusu** [comment]
Everything in my PC, including language, locale, keyboard layout and WoW, is French. I do have an English language pack installed but it is disabled, I don't think it should interfere.
