### ISSUE TITLE
Button on worldmap overlaps close button when used with Leatrix Maps addon

### ISSUE THREAD

**Issue by RENgOLD** [TheKrowi/Krowi_AchievementFilter#69]
Krowi's button on worldmap overlaps Leatrix Maps close button.
Leatrix Maps is quite popular addon (10m+ downloads on curceforge), so it would be nice to move a little Krowi's button or add option to hide this button.
![image](https://user-images.githubusercontent.com/1100128/202345403-365751b0-a00a-4ce1-b49e-7fab9f1f3d4e.png)

**Comment by RENgOLD** [comment]
Oh, my bad, i'm sorry, just missed that option to hide world map icon. 
NWM :)

**Comment by TheKrowi** [comment]
Hey @RENgOLD , this is not an issue with KAF on Leatrix Maps. It's an issue with a library that adds the button. I'm in conversation with Leatricx on how to solve this not only for KAF but all addons using the library.

**Comment by TheKrowi** [comment]
Should be fixed so enabling the button again should work: https://github.com/leatrix/leatrix-maps-wrath/commit/bd537fca3db797eeb6a747cc7f9454f7b85a47d8
