### ISSUE TITLE
Feature Request: Custom lists

### ISSUE THREAD

**Issue by GrimNotepad** [TheKrowi/Krowi_AchievementFilter#70]
Coming from Overachiever, one thing I really like was the ability to add a bunch of cheevos to a watchlist, like a "To-Do" list. 
I would look forward to seeing if something like that

**Comment by Malivil** [comment]
KAF has a concept of "focused" achievements which is the equivalent of a watch list. I _believe_ the focused category shows under Special but you may need/want to change the settings for that.
