### ISSUE TITLE
Feature request: Full search window

### ISSUE THREAD

**Issue by GurliGebis** [TheKrowi/Krowi_AchievementFilter#72]
The only thing I'm missing from Overachiever, which I have been using up until now is the search tab.
I know there is a search feature here, but on the list it shows, when you click on an achievement, it jumps to it, and closes the search dialog.

Would it be possible to implement a search tab, where the result is shown, where you can expand them and read about them, without being moved away.

Since the addon is no longer working, I have attached a screenshot of how it looked:

![6YGBpUw](https://user-images.githubusercontent.com/13592619/202752548-fed19149-5cb8-40db-b20c-2488c163a9ff.jpg)

**Comment by TheKrowi** [comment]
This was implemented in https://github.com/TheKrowi/Krowi_AchievementFilter/commit/754ab4e103aa3839258a06c8eb82a053b6d4ec59 and released with [version 50.0](https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/50.0)

**Comment by GurliGebis** [comment]
Thanks you
