### ISSUE TITLE
"krowi_achievementfilter has been blocked from an action..."

### ISSUE THREAD

**Issue by IvanDoomer** [TheKrowi/Krowi_AchievementFilter#73]
Several times the addon blocks action bars

![image](https://user-images.githubusercontent.com/15795767/202814973-6cde87ce-9745-4955-8839-b73c2eb1c13f.png)

Enabling LUA errors does not report failure

**Comment by TheKrowi** [comment]
This is unfortunately still a blizzard problem. Addon creators can't do anything about it :/

**Comment by Mithras2801** [comment]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Krowi_AchievementFilter' tried to call the protected function 'SpellStopCasting()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SpellStopCasting'
[string "@FrameXML/UIParent.lua"]:4063: in function `ToggleGameMenu'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:336: in function `TransitionBackOpeningPanel'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:325: in function `ExitWithCommit'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:301: in function `Close'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:71: in function <SharedXML/Settings/Blizzard_SettingsPanel.lua:70>

**Comment by Rezy942** [comment]
Constantly getting this myself. Every single day :c

**Comment by TheKrowi** [comment]
This one should be resolved by now, if not, please open a new ticket.
