### ISSUE TITLE
Classic 48.2 Error

### ISSUE THREAD

**Issue by tehKD** [TheKrowi/Krowi_AchievementFilter#78]
1x Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:33: attempt to call method 'Load' (a nil value)
[string "@Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua"]:33: in function `LoadWithBlizzard_AchievementUI'
[string "@Interface\AddOns\Krowi_AchievementFilter\Krowi_AchievementFilter-48.2.lua"]:80: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:77>
[string "@Interface\AddOns\Krowi_AchievementFilter\Krowi_AchievementFilter-48.2.lua"]:122: in function <...\Krowi_AchievementFilter\Krowi_AchievementFilter.lua:111>

Locals:
self = <table> {
 HookShowSubFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:74
 CategoriesFrame = KrowiAF_CategoriesFrame {
 }
 SetAchievementFrameHeight = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:141
 HookBaseTabOnClick = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:80
 PrepareTabsOrder = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:291
 RefreshView = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:452
 SummaryFrame = KrowiAF_AchievementFrameSummaryFrame {
 }
 AlertSystem = <table> {
 }
 ShowStatusBarTooltip = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:301
 LoadOldAchievementFrameTabsCompatibility = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:426
 SetCloseButtonOnKeyDown = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:116
 LoadWithAddon = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:11
 Tabs = <table> {
 }
 AchievementsObjectives = KrowiAF_AchievementsObjectives {
 }
 ResetAchievementWindowPosition = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:107
 ShowSubFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:93
 SideButton = <table> {
 }
 FilterButton = KrowiAF_AchievementFrameFilterButton {
 }
 Calendar = <table> {
 }
 SetFrameToLastPosition = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:436
 SetAchievementFrameWidth = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:131
 Search = <table> {
 }
 RightClickMenu = <table> {
 }
 AchievementsFrame = KrowiAF_AchievementsFrame {
 }
 LoadOldAchievementFrameCompatibility = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:409
 TabsOrderGetActiveKeys = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:326
 AchievementTooltip = <table> {
 }
 AchievementFrameTabButton = <table> {
 }
 AddDataToBlizzardTabs = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:277
 GetSafeScrollChildBottom = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:155
 AchievementFrameHeader = <table> {
 }
 DataManagerFrame = KrowiAF_DataManagerFrame {
 }
 WorldMapButton = Krowi_WorldMapButtons1 {
 }
 SelectTab = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:183
 LoadWrathClassicAchievementFrameChanges = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:394
 LoadWithBlizzard_AchievementUI = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:22
 SubFrames = <table> {
 }
 ResetAchievementFrameHeight = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:148
 ShowHideTabs = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:232
 ToggleAchievementFrame = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:194
 GameTooltipProgressBar = Krowi_ProgressBar1 {
 }
 ResetAchievementFrameWidth = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\GUI.lua:135
 SideButtonSystem = <table> {
 }
}
(*temporary) = nil
(*temporary) = KrowiAF_AchievementsObjectives {
 0 = <userdata>
 DisplayCriteria = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:313
 ResetProgressBars = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:18
 SetTextPoints = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:262
 ResetAll = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:33
 ResetMiniAchievements = <function> defined @Interface\AddOns\Krowi_AchievementFilter\GUI\AchievementButton\AchievementsObjectivesMixin.lua:22
 ResetTextCriteria = <function> defined @Interface\AddOns\Krowi_AchievementF

**Comment by TheKrowi** [comment]
1. Are you using GW2 addon? This is known to cause this error.
2. Any other addons that might load the achievement view before KAF is able to load?
3. Have you tried without any other addons enabled?

**Comment by tehKD** [comment]
1. No
2. No
3. Yes, and i had no more errors... that said, i had no issues before the latest update to 48.2.

**Comment by TheKrowi** [comment]
Unfortunately since it's working fine with only KAF enabled, there is not much I can do unless you find the addon that is causing this issue.

**Comment by TheKrowi** [comment]
I'm not able to reproduce this issue. Please provide a detailed list of steps what I should do.

Additional info to add is:

1. Other addons that are needed to cause this issue.

@gelsbern please provide more info here as well if you have.
