### ISSUE TITLE
Feature Request: Remember position in tab/category/page

### ISSUE THREAD

**Issue by Taizunz** [TheKrowi/Krowi_AchievementFilter#79]
I'd love if there was a way for your addon to remember the tab/category/page and scroll position I was last on in one of the tabs that are added by your addon, so that I don't have to navigate back to it every time I reopen the achievement interface.

For reference, I know about the "Reset view on open" setting found in your Key Bindings settings page, but disabling this only affects the default Achievements tab and nothing else.

**Comment by TheKrowi** [comment]
You can keybind other tabs. This should meet your needs. See options -> General -> Keybindings

**Comment by Taizunz** [comment]
Not entirely. When using the search bar and clicking on an achievement via that, it still resets the position back to the summary page when reopening the interface.

**Comment by TheKrowi** [comment]
This was implemented in https://github.com/TheKrowi/Krowi_AchievementFilter/commit/90f3b45f2fccb9b51385cb2e13545f3a8dde3df1 and released with [version 50.0](https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/50.0)
