### ISSUE TITLE
Feature Request: Reward, Criteria and Description search

### ISSUE THREAD

**Issue by Dathwada** [TheKrowi/Krowi_AchievementFilter#84]
I would like to request the feature that you can search for rewards, criteria and descriptions, like in Overachiever (this addon seems unfortunately no longer be maintained)

**Comment by TheKrowi** [comment]
Latest version can search id, reward, description and name. There is a small button on the searchbox.

Criteria is not yet added cause it is a lot more intense to search.

**Comment by Dathwada** [comment]
Ooh thanks, haven't seen this button.

**Comment by TheKrowi** [comment]
This was implemented in https://github.com/TheKrowi/Krowi_AchievementFilter/commit/9ba054daa5788c68ccd5575a52f4929a25f7e365 and released with [version 49.4](https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/49.4)
