### ISSUE TITLE
Suggestion: Notify about current Hunts / Community feasts

### ISSUE THREAD

**Issue by layzsmurf** [TheKrowi/Krowi_AchievementFilter#91]
I like the feature that notifies me about ongoing invasions so I hope you could extend it towards hunts and community feasts even though they are not necessarily achievement related.

In theory they happen every 4 hours and should be unlocked account wide, but I have not spotted a community feast for two days.

**Comment by TheKrowi** [comment]
Hey,

I won't add reminders that are not related to any achievement. If there are related achievements, let me know and I can add these events.

**Comment by filliph** [comment]
From a quick wowhead search:
https://www.wowhead.com/achievement=16544/grand-hunter
https://www.wowhead.com/achievement=16542/the-disgruntled-hunter
https://www.wowhead.com/achievement=16540/hunt-master
https://www.wowhead.com/achievement=16545/the-best-at-what-i-do
(and probably more)

https://www.wowhead.com/achievement=16444/leftovers-revenge
https://www.wowhead.com/achievement=16443/soupervisor

**Comment by TheKrowi** [comment]
Some progress 
![image](https://user-images.githubusercontent.com/22818581/206713861-bd09ebca-8793-4706-9336-44c7f9954273.png)

**Comment by TheKrowi** [comment]
This was implemented in https://github.com/TheKrowi/Krowi_AchievementFilter/commit/db447e54eba679db9dd62833ecc8a53cb34877f1 and https://github.com/TheKrowi/Krowi_AchievementFilter/commit/0f1ef538f425d72a8ef4b60a693f7c65e2966859 and released with [version 49.3](https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/49.3) and [version 49.4](https://github.com/TheKrowi/Krowi_AchievementFilter/releases/tag/49.4)
