### ISSUE TITLE
Krowi_AchievementFilter/Globals.lua:211: attempt to index local 'achievement' (a nil value)

### ISSUE THREAD

**Issue by tatatada** [TheKrowi/Krowi_AchievementFilter#97]
2x Krowi_AchievementFilter/Globals.lua:211: attempt to index local 'achievement' (a nil value)
[string "@Krowi_AchievementFilter/Globals.lua"]:211: in function `func'
[string "@Krowi_AchievementFilter/Data/Data.lua"]:64: in function <Krowi_AchievementFilter/Data/Data.lua:58>
[string "@Krowi_AchievementFilter/Data/Data.lua"]:81: in function `LoadExcludedAchievements'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:80: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:73>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:117: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:112>
[string "=[C]"]: in function `LoadAddOn'
[string "@Krowi_AchievementFilter/GUI/Misc/WorldMapButton/WorldMapButtonMixin.lua"]:62: in function `Refresh'
[string "@HandyNotes_BattleForAzerothTreasures/handler/lib/Krowi_WorldMapButtons-1.4.lua"]:93: in function <...hTreasures/handler/lib/Krowi_WorldMapButtons-1.4.lua:92>
[string "=[C]"]: ?
[string "=[C]"]: in function `RefreshOverlayFrames'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:233: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
...
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:3189: in function <FrameXML/UIParent.lua:3175>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:440: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:439>
[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
achievement = nil
update = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'achievement' (a nil value)"
addon = <table> {
 ReplaceVarsWithReloadReq = <function> defined @Krowi_AchievementFilter/Globals.lua:537
 WorldMapButtons = <table> {
 }
 GUI = <table> {
 }
 SearchOptions = <table> {
 }
 ExcludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:210
 Data = <table> {
 }
 Filters = <table> {
 }
 Diagnostics = <table> {
 }
 IsShadowlandsRetail = false
 IsCustomModifierKeyDown = <function> defined @Krowi_AchievementFilter/Globals.lua:667
 DelayObjects = <table> {
 }
 Objects = <table> {
 }
 DelayFunction = <function> defined @Krowi_AchievementFilter/Globals.lua:640
 ClearWatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:136
 OnAchievementEarned = <function> defined @Krowi_AchievementFilter/Globals.lua:361
 Options = <table> {
 }
 TooltipData = <table> {
 }
 EventData = <table> {
 }
 GlobalStrings = <table> {
 }
 ChangeAchievementMicroButtonOnClick = <function> defined @Krowi_AchievementFilter/Globals.lua:621
 GetUsableSets = <function> defined @Krowi_AchievementFilter/Globals.lua:591
 Modifiers = <table> {
 }
 MakeWindowMovable = <function> defined @Krowi_AchievementFilter/Globals.lua:517
 GetNextAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:561
 ExtraWrathStrings = <table> {
 }
 Colors = <table> {
 }
 GetInstanceInfoName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:10
 GetMapName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:38
 GetAchievementInfo = <function> defined @Krowi_AchievementFilter/Globals.lua:550
 Util = <table> {
 }
 MetaData = <table> {
 }
 GetFirstAchievementId = <function> defined @Krowi_AchievementFilter/Globals.lua:3
 GetSecondsSince = <function> defined @Krowi_AchievementFilter/Globals.lua:527
 WatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:160
 InGuildView = <function> defined @Krowi_AchievementFilter/Globals.lua:12
 TrackingAchievements = <table> {
 }
 GetAchievementsInZone = <function> defined @Krowi_AchievementFilter/Globals.lua:20
 MakeWindowStatic = <function> defined @Krowi_AchievementFilter/Globals.lua:477
 GetVariantSetIDs = <function> defined @Krowi_AchievementFilter/Globals.lua:603
 GetLFGDungeonInfo = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:34
 ResetCache = <function> defined @Krowi_AchievementFilter/Globals.lua:357
 BuildCache = <function> defined @Krowi_AchievementFilter/Globals.lua:325
 OverwriteFunctions = <function> defined @Krowi_AchievementFilter/Globals.lua:377
 Plugins = <table> {
 }
 L = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Krowi_AchievementFilter/Globals.lua:16
 HookAchievementFrameOnShow = <function> defined @Krowi_AchievementFilter/Globals.lua:449
 GetAchievementNumbers = <function> defined @Krowi_AchievementFilter/Globals.lua:51
 GetCategoryInfoTitle = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:22
 IncludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:187
 AddToTrackingAchievementsCategories = <function> defined @Krowi_AchievementFilter/Globals.lua:174
 Event = <table> {
 }
 TabsOrder = <table> {
 }
 IsDragonflightRetail = true
 Tutorials = <table> {
 }
 GetCovenantName = <function> defined @Krowi_Achieveme

**Comment by TheKrowi** [comment]
Hey, I noticed from the error log it's something related to loading excluded achievements when the world map is opened. Could you give me some steps on how to reproduce it and also when it not happens?

Like, does it happen if you load ingame and open the world map first but not if you open the achievement window and then the world map?
Have you tested it with only KAF enabled?
Things like that.

**Comment by tatatada** [comment]
11x Krowi_AchievementFilter/Globals.lua:211: attempt to index local 'achievement' (a nil value)
[string "@Krowi_AchievementFilter/Globals.lua"]:211: in function `func'
[string "@Krowi_AchievementFilter/Data/Data.lua"]:64: in function <Krowi_AchievementFilter/Data/Data.lua:58>
[string "@Krowi_AchievementFilter/Data/Data.lua"]:81: in function `LoadExcludedAchievements'
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:80: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:73>
[string "@Krowi_AchievementFilter/Krowi_AchievementFilter.lua"]:117: in function <.../Krowi_AchievementFilter/Krowi_AchievementFilter.lua:112>
[string "=[C]"]: in function `LoadAddOn'
[string "@Krowi_AchievementFilter/GUI/Misc/WorldMapButton/WorldMapButtonMixin.lua"]:62: in function `Refresh'
[string "@HandyNotes_BattleForAzerothTreasures/handler/lib/Krowi_WorldMapButtons-1.4.lua"]:93: in function <...hTreasures/handler/lib/Krowi_WorldMapButtons-1.4.lua:92>
[string "=[C]"]: ?
[string "=[C]"]: in function `RefreshOverlayFrames'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:233: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
...
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:3189: in function <FrameXML/UIParent.lua:3175>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:440: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:439>
[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
achievement = nil
update = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'achievement' (a nil value)"
addon = <table> {
 ReplaceVarsWithReloadReq = <function> defined @Krowi_AchievementFilter/Globals.lua:537
 WorldMapButtons = <table> {
 }
 GUI = <table> {
 }
 SearchOptions = <table> {
 }
 ExcludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:210
 Data = <table> {
 }
 Filters = <table> {
 }
 Diagnostics = <table> {
 }
 IsShadowlandsRetail = false
 IsCustomModifierKeyDown = <function> defined @Krowi_AchievementFilter/Globals.lua:667
 DelayObjects = <table> {
 }
 Objects = <table> {
 }
 DelayFunction = <function> defined @Krowi_AchievementFilter/Globals.lua:640
 ClearWatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:136
 OnAchievementEarned = <function> defined @Krowi_AchievementFilter/Globals.lua:361
 Options = <table> {
 }
 TooltipData = <table> {
 }
 EventData = <table> {
 }
 GlobalStrings = <table> {
 }
 ChangeAchievementMicroButtonOnClick = <function> defined @Krowi_AchievementFilter/Globals.lua:621
 GetUsableSets = <function> defined @Krowi_AchievementFilter/Globals.lua:591
 Modifiers = <table> {
 }
 MakeWindowMovable = <function> defined @Krowi_AchievementFilter/Globals.lua:517
 GetNextAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:561
 ExtraWrathStrings = <table> {
 }
 Colors = <table> {
 }
 GetInstanceInfoName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:10
 GetMapName = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:38
 GetAchievementInfo = <function> defined @Krowi_AchievementFilter/Globals.lua:550
 Util = <table> {
 }
 MetaData = <table> {
 }
 GetFirstAchievementId = <function> defined @Krowi_AchievementFilter/Globals.lua:3
 GetSecondsSince = <function> defined @Krowi_AchievementFilter/Globals.lua:527
 WatchAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:160
 InGuildView = <function> defined @Krowi_AchievementFilter/Globals.lua:12
 TrackingAchievements = <table> {
 }
 GetAchievementsInZone = <function> defined @Krowi_AchievementFilter/Globals.lua:20
 MakeWindowStatic = <function> defined @Krowi_AchievementFilter/Globals.lua:477
 GetVariantSetIDs = <function> defined @Krowi_AchievementFilter/Globals.lua:603
 GetLFGDungeonInfo = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:34
 ResetCache = <function> defined @Krowi_AchievementFilter/Globals.lua:357
 BuildCache = <function> defined @Krowi_AchievementFilter/Globals.lua:325
 OverwriteFunctions = <function> defined @Krowi_AchievementFilter/Globals.lua:377
 Plugins = <table> {
 }
 L = <table> {
 }
 Icon = <table> {
 }
 Credits = <table> {
 }
 GetActiveCovenant = <function> defined @Krowi_AchievementFilter/Globals.lua:16
 HookAchievementFrameOnShow = <function> defined @Krowi_AchievementFilter/Globals.lua:449
 GetAchievementNumbers = <function> defined @Krowi_AchievementFilter/Globals.lua:51
 GetCategoryInfoTitle = <function> defined @Krowi_AchievementFilter/Localization/GlobalStrings.lua:22
 IncludeAchievement = <function> defined @Krowi_AchievementFilter/Globals.lua:187
 AddToTrackingAchievementsCategories = <function> defined @Krowi_AchievementFilter/Globals.lua:174
 Event = <table> {
 }
 TabsOrder = <table> {
 }
 IsDragonflightRetail = true
 Tutorials = <table> {
 }
 GetCovenantName = <function> defined @Krowi_Achieveme

**Comment by TheKrowi** [comment]
Fixed in https://github.com/TheKrowi/Krowi_AchievementFilter/commit/39545a081a0fad394d49acd615cb214afe437878
